### ISSUE TITLE
Logger crashes when redact is required at max depth + 1

### ISSUE THREAD

**Issue by brian-captain-crosby** [seek-oss/logger#14]
## Description

The logger fails when redact is configured for a field one level deeper than the max object depth

```
TypeError: Cannot assign to read only property '0' of string '[Object]'
    at groupRedact (/workdir/node_modules/fast-redact/lib/modifiers.js:38:19)
    at Object.eval (eval at redactor (/workdir/node_modules/fast-redact/lib/redactor.js:1:1), <anonymous>:18:36)
    at Pino.asJson (/workdir/node_modules/@seek/logger/node_modules/pino/lib/tools.js:139:45)
    at Pino.write (/workdir/node_modules/@seek/logger/node_modules/pino/lib/proto.js:166:28)
    at Pino.LOG [as warn] (/workdir/node_modules/@seek/logger/node_modules/pino/lib/tools.js:55:21)
    at runMicrotasks (<anonymous>) 
```

At the max object depth, the field is set to `'[Object]'`. When the redact happens, it crashes.

## Steps to reproduce (for bugs)

```
testLog(
  test,
  'should redact array items',
  {
    a: { b: [{ name: 'Bob' }] },
  },
  {
    name: 'my-app',
    a: { b: ['[Redacted]'] },
    level: 30,
  },
  'info',
  {
    redact: {
      paths: ['a.b.*'],
    },
    maxObjectDepth: 2,
  } as LoggerOptions,
);
```

**Comment by 72636c** [comment]
That looks nasty but on a cursory look I think the actual fix needs to applied in pino / dtrim / even further upstream in fast-redact. In the meantime, do you actually need the redact paths?

**Comment by brian-captain-crosby** [comment]
Yeah, I didn't think anything could be done in the logger to avoid the issue, but I thought I'd create an issue to raise awareness.

We need the redact paths to filter out some PII. We got around the error by setting a higher `maxObjectDepth`.

**Comment by runk** [comment]
This looks to me like a `fast-redact` bug, which cannot comprehend the string value. 

```
testLog(
  test,
  'should redact array items',
  {
    a: { b: "bob" },
  },
  {
    name: 'my-app',
    a: { b: '[Redacted]' },
    level: 30,
  },
  'info',
  {
    redact: {
      paths: ['a.b.*'],
    },
    maxObjectDepth: 99,
  } as LoggerOptions,
);
```

same outcome

```
TypeError: Cannot assign to read only property '0' of string 'bob'

at groupRedact (node_modules/fast-redact/lib/modifiers.js:38:19)
      at Object.eval (eval at redactor (node_modules/fast-redact/lib/redactor.js:9:18), <anonymous>:16:36)
      at Pino.asJson (node_modules/pino/lib/tools.js:139:45)
      at Pino.write (node_modules/pino/lib/proto.js:166:28)
      at Pino.LOG [as info] (node_modules/pino/lib/tools.js:55:21)
```

**Comment by 72636c** [comment]
Thanks for the detective work @runk! https://github.com/davidmarkclements/fast-redact/issues/31

**Comment by 72636c** [comment]
@ConradLang I don't have merge permissions on that repo.
